/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DailyOperationsRouteImport } from './routes/daily-operations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as MusammiRouteImport } from './routes/musammi'
import { Route as ProgramSupervisorRouteImport } from './routes/program-supervisor'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SecretaryRouteImport } from './routes/secretary'
import { Route as StaffAttendanceRouteImport } from './routes/staff-attendance'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as TeacherRouteImport } from './routes/teacher'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyOperationsRoute = DailyOperationsRouteImport.update({
  id: '/daily-operations',
  path: '/daily-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const MusammiRoute = MusammiRouteImport.update({
  id: '/musammi',
  path: '/musammi',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramSupervisorRoute = ProgramSupervisorRouteImport.update({
  id: '/program-supervisor',
  path: '/program-supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretaryRoute = SecretaryRouteImport.update({
  id: '/secretary',
  path: '/secretary',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAttendanceRoute = StaffAttendanceRouteImport.update({
  id: '/staff-attendance',
  path: '/staff-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/daily-operations': typeof DailyOperationsRoute
  '/dashboard': typeof DashboardRoute
  '/manager': typeof ManagerRoute
  '/musammi': typeof MusammiRoute
  '/program-supervisor': typeof ProgramSupervisorRoute
  '/register': typeof RegisterRoute
  '/secretary': typeof SecretaryRoute
  '/staff-attendance': typeof StaffAttendanceRoute
  '/student': typeof StudentRoute
  '/supervisor': typeof SupervisorRoute
  '/teacher': typeof TeacherRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/daily-operations': typeof DailyOperationsRoute
  '/dashboard': typeof DashboardRoute
  '/manager': typeof ManagerRoute
  '/musammi': typeof MusammiRoute
  '/program-supervisor': typeof ProgramSupervisorRoute
  '/register': typeof RegisterRoute
  '/secretary': typeof SecretaryRoute
  '/staff-attendance': typeof StaffAttendanceRoute
  '/student': typeof StudentRoute
  '/supervisor': typeof SupervisorRoute
  '/teacher': typeof TeacherRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/daily-operations': typeof DailyOperationsRoute
  '/dashboard': typeof DashboardRoute
  '/manager': typeof ManagerRoute
  '/musammi': typeof MusammiRoute
  '/program-supervisor': typeof ProgramSupervisorRoute
  '/register': typeof RegisterRoute
  '/secretary': typeof SecretaryRoute
  '/staff-attendance': typeof StaffAttendanceRoute
  '/student': typeof StudentRoute
  '/supervisor': typeof SupervisorRoute
  '/teacher': typeof TeacherRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/daily-operations'
    | '/dashboard'
    | '/manager'
    | '/musammi'
    | '/program-supervisor'
    | '/register'
    | '/secretary'
    | '/staff-attendance'
    | '/student'
    | '/supervisor'
    | '/teacher'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/daily-operations'
    | '/dashboard'
    | '/manager'
    | '/musammi'
    | '/program-supervisor'
    | '/register'
    | '/secretary'
    | '/staff-attendance'
    | '/student'
    | '/supervisor'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/daily-operations'
    | '/dashboard'
    | '/manager'
    | '/musammi'
    | '/program-supervisor'
    | '/register'
    | '/secretary'
    | '/staff-attendance'
    | '/student'
    | '/supervisor'
    | '/teacher'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DailyOperationsRoute: typeof DailyOperationsRoute
  DashboardRoute: typeof DashboardRoute
  ManagerRoute: typeof ManagerRoute
  MusammiRoute: typeof MusammiRoute
  ProgramSupervisorRoute: typeof ProgramSupervisorRoute
  RegisterRoute: typeof RegisterRoute
  SecretaryRoute: typeof SecretaryRoute
  StaffAttendanceRoute: typeof StaffAttendanceRoute
  StudentRoute: typeof StudentRoute
  SupervisorRoute: typeof SupervisorRoute
  TeacherRoute: typeof TeacherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-operations': {
      id: '/daily-operations'
      path: '/daily-operations'
      fullPath: '/daily-operations'
      preLoaderRoute: typeof DailyOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musammi': {
      id: '/musammi'
      path: '/musammi'
      fullPath: '/musammi'
      preLoaderRoute: typeof MusammiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-supervisor': {
      id: '/program-supervisor'
      path: '/program-supervisor'
      fullPath: '/program-supervisor'
      preLoaderRoute: typeof ProgramSupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secretary': {
      id: '/secretary'
      path: '/secretary'
      fullPath: '/secretary'
      preLoaderRoute: typeof SecretaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-attendance': {
      id: '/staff-attendance'
      path: '/staff-attendance'
      fullPath: '/staff-attendance'
      preLoaderRoute: typeof StaffAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DailyOperationsRoute: DailyOperationsRoute,
  DashboardRoute: DashboardRoute,
  ManagerRoute: ManagerRoute,
  MusammiRoute: MusammiRoute,
  ProgramSupervisorRoute: ProgramSupervisorRoute,
  RegisterRoute: RegisterRoute,
  SecretaryRoute: SecretaryRoute,
  StaffAttendanceRoute: StaffAttendanceRoute,
  StudentRoute: StudentRoute,
  SupervisorRoute: SupervisorRoute,
  TeacherRoute: TeacherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
