/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantSlugRouteRouteImport } from './routes/$tenantSlug/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DailyOperationsRouteImport } from './routes/daily-operations'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as KioskRouteImport } from './routes/kiosk'
import { Route as ManagerRouteImport } from './routes/manager'
import { Route as MusammiRouteImport } from './routes/musammi'
import { Route as PlatformAdminRouteImport } from './routes/platform-admin'
import { Route as PrelaunchAuditRouteImport } from './routes/prelaunch-audit'
import { Route as ProgramSupervisorRouteImport } from './routes/program-supervisor'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as SecretaryRouteImport } from './routes/secretary'
import { Route as StaffAttendanceRouteImport } from './routes/staff-attendance'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as TenantSlugIndexRouteImport } from './routes/$tenantSlug/index'
import { Route as TenantSlugKioskRouteImport } from './routes/$tenantSlug/kiosk'
import { Route as TenantSlugManagerRouteImport } from './routes/$tenantSlug/manager'
import { Route as TenantSlugMusammiRouteImport } from './routes/$tenantSlug/musammi'
import { Route as TenantSlugProgramSupervisorRouteImport } from './routes/$tenantSlug/program-supervisor'
import { Route as TenantSlugSecretaryRouteImport } from './routes/$tenantSlug/secretary'
import { Route as TenantSlugStaffAttendanceRouteImport } from './routes/$tenantSlug/staff-attendance'
import { Route as TenantSlugStudentRouteImport } from './routes/$tenantSlug/student'
import { Route as TenantSlugSupervisorRouteImport } from './routes/$tenantSlug/supervisor'
import { Route as TenantSlugTeacherRouteImport } from './routes/$tenantSlug/teacher'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSlugRouteRoute = TenantSlugRouteRouteImport.update({
  id: '/$tenantSlug',
  path: '/$tenantSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyOperationsRoute = DailyOperationsRouteImport.update({
  id: '/daily-operations',
  path: '/daily-operations',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerRoute = ManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => rootRouteImport,
} as any)
const MusammiRoute = MusammiRouteImport.update({
  id: '/musammi',
  path: '/musammi',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformAdminRoute = PlatformAdminRouteImport.update({
  id: '/platform-admin',
  path: '/platform-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PrelaunchAuditRoute = PrelaunchAuditRouteImport.update({
  id: '/prelaunch-audit',
  path: '/prelaunch-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramSupervisorRoute = ProgramSupervisorRouteImport.update({
  id: '/program-supervisor',
  path: '/program-supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretaryRoute = SecretaryRouteImport.update({
  id: '/secretary',
  path: '/secretary',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffAttendanceRoute = StaffAttendanceRouteImport.update({
  id: '/staff-attendance',
  path: '/staff-attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantSlugIndexRoute = TenantSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const TenantSlugKioskRoute = TenantSlugKioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const TenantSlugManagerRoute = TenantSlugManagerRouteImport.update({
  id: '/manager',
  path: '/manager',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const TenantSlugMusammiRoute = TenantSlugMusammiRouteImport.update({
  id: '/musammi',
  path: '/musammi',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const TenantSlugProgramSupervisorRoute =
  TenantSlugProgramSupervisorRouteImport.update({
    id: '/program-supervisor',
    path: '/program-supervisor',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugSecretaryRoute = TenantSlugSecretaryRouteImport.update({
  id: '/secretary',
  path: '/secretary',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const TenantSlugStaffAttendanceRoute =
  TenantSlugStaffAttendanceRouteImport.update({
    id: '/staff-attendance',
    path: '/staff-attendance',
    getParentRoute: () => TenantSlugRouteRoute,
  } as any)
const TenantSlugStudentRoute = TenantSlugStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const TenantSlugSupervisorRoute = TenantSlugSupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)
const TenantSlugTeacherRoute = TenantSlugTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => TenantSlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$tenantSlug': typeof TenantSlugRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/daily-operations': typeof DailyOperationsRoute
  '/dashboard': typeof DashboardRoute
  '/kiosk': typeof KioskRoute
  '/manager': typeof ManagerRoute
  '/musammi': typeof MusammiRoute
  '/platform-admin': typeof PlatformAdminRoute
  '/prelaunch-audit': typeof PrelaunchAuditRoute
  '/program-supervisor': typeof ProgramSupervisorRoute
  '/register': typeof RegisterRoute
  '/secretary': typeof SecretaryRoute
  '/staff-attendance': typeof StaffAttendanceRoute
  '/student': typeof StudentRoute
  '/supervisor': typeof SupervisorRoute
  '/teacher': typeof TeacherRoute
  '/$tenantSlug/kiosk': typeof TenantSlugKioskRoute
  '/$tenantSlug/manager': typeof TenantSlugManagerRoute
  '/$tenantSlug/musammi': typeof TenantSlugMusammiRoute
  '/$tenantSlug/program-supervisor': typeof TenantSlugProgramSupervisorRoute
  '/$tenantSlug/secretary': typeof TenantSlugSecretaryRoute
  '/$tenantSlug/staff-attendance': typeof TenantSlugStaffAttendanceRoute
  '/$tenantSlug/student': typeof TenantSlugStudentRoute
  '/$tenantSlug/supervisor': typeof TenantSlugSupervisorRoute
  '/$tenantSlug/teacher': typeof TenantSlugTeacherRoute
  '/$tenantSlug/': typeof TenantSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/daily-operations': typeof DailyOperationsRoute
  '/dashboard': typeof DashboardRoute
  '/kiosk': typeof KioskRoute
  '/manager': typeof ManagerRoute
  '/musammi': typeof MusammiRoute
  '/platform-admin': typeof PlatformAdminRoute
  '/prelaunch-audit': typeof PrelaunchAuditRoute
  '/program-supervisor': typeof ProgramSupervisorRoute
  '/register': typeof RegisterRoute
  '/secretary': typeof SecretaryRoute
  '/staff-attendance': typeof StaffAttendanceRoute
  '/student': typeof StudentRoute
  '/supervisor': typeof SupervisorRoute
  '/teacher': typeof TeacherRoute
  '/$tenantSlug/kiosk': typeof TenantSlugKioskRoute
  '/$tenantSlug/manager': typeof TenantSlugManagerRoute
  '/$tenantSlug/musammi': typeof TenantSlugMusammiRoute
  '/$tenantSlug/program-supervisor': typeof TenantSlugProgramSupervisorRoute
  '/$tenantSlug/secretary': typeof TenantSlugSecretaryRoute
  '/$tenantSlug/staff-attendance': typeof TenantSlugStaffAttendanceRoute
  '/$tenantSlug/student': typeof TenantSlugStudentRoute
  '/$tenantSlug/supervisor': typeof TenantSlugSupervisorRoute
  '/$tenantSlug/teacher': typeof TenantSlugTeacherRoute
  '/$tenantSlug': typeof TenantSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$tenantSlug': typeof TenantSlugRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/daily-operations': typeof DailyOperationsRoute
  '/dashboard': typeof DashboardRoute
  '/kiosk': typeof KioskRoute
  '/manager': typeof ManagerRoute
  '/musammi': typeof MusammiRoute
  '/platform-admin': typeof PlatformAdminRoute
  '/prelaunch-audit': typeof PrelaunchAuditRoute
  '/program-supervisor': typeof ProgramSupervisorRoute
  '/register': typeof RegisterRoute
  '/secretary': typeof SecretaryRoute
  '/staff-attendance': typeof StaffAttendanceRoute
  '/student': typeof StudentRoute
  '/supervisor': typeof SupervisorRoute
  '/teacher': typeof TeacherRoute
  '/$tenantSlug/kiosk': typeof TenantSlugKioskRoute
  '/$tenantSlug/manager': typeof TenantSlugManagerRoute
  '/$tenantSlug/musammi': typeof TenantSlugMusammiRoute
  '/$tenantSlug/program-supervisor': typeof TenantSlugProgramSupervisorRoute
  '/$tenantSlug/secretary': typeof TenantSlugSecretaryRoute
  '/$tenantSlug/staff-attendance': typeof TenantSlugStaffAttendanceRoute
  '/$tenantSlug/student': typeof TenantSlugStudentRoute
  '/$tenantSlug/supervisor': typeof TenantSlugSupervisorRoute
  '/$tenantSlug/teacher': typeof TenantSlugTeacherRoute
  '/$tenantSlug/': typeof TenantSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$tenantSlug'
    | '/admin'
    | '/daily-operations'
    | '/dashboard'
    | '/kiosk'
    | '/manager'
    | '/musammi'
    | '/platform-admin'
    | '/prelaunch-audit'
    | '/program-supervisor'
    | '/register'
    | '/secretary'
    | '/staff-attendance'
    | '/student'
    | '/supervisor'
    | '/teacher'
    | '/$tenantSlug/kiosk'
    | '/$tenantSlug/manager'
    | '/$tenantSlug/musammi'
    | '/$tenantSlug/program-supervisor'
    | '/$tenantSlug/secretary'
    | '/$tenantSlug/staff-attendance'
    | '/$tenantSlug/student'
    | '/$tenantSlug/supervisor'
    | '/$tenantSlug/teacher'
    | '/$tenantSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/daily-operations'
    | '/dashboard'
    | '/kiosk'
    | '/manager'
    | '/musammi'
    | '/platform-admin'
    | '/prelaunch-audit'
    | '/program-supervisor'
    | '/register'
    | '/secretary'
    | '/staff-attendance'
    | '/student'
    | '/supervisor'
    | '/teacher'
    | '/$tenantSlug/kiosk'
    | '/$tenantSlug/manager'
    | '/$tenantSlug/musammi'
    | '/$tenantSlug/program-supervisor'
    | '/$tenantSlug/secretary'
    | '/$tenantSlug/staff-attendance'
    | '/$tenantSlug/student'
    | '/$tenantSlug/supervisor'
    | '/$tenantSlug/teacher'
    | '/$tenantSlug'
  id:
    | '__root__'
    | '/'
    | '/$tenantSlug'
    | '/admin'
    | '/daily-operations'
    | '/dashboard'
    | '/kiosk'
    | '/manager'
    | '/musammi'
    | '/platform-admin'
    | '/prelaunch-audit'
    | '/program-supervisor'
    | '/register'
    | '/secretary'
    | '/staff-attendance'
    | '/student'
    | '/supervisor'
    | '/teacher'
    | '/$tenantSlug/kiosk'
    | '/$tenantSlug/manager'
    | '/$tenantSlug/musammi'
    | '/$tenantSlug/program-supervisor'
    | '/$tenantSlug/secretary'
    | '/$tenantSlug/staff-attendance'
    | '/$tenantSlug/student'
    | '/$tenantSlug/supervisor'
    | '/$tenantSlug/teacher'
    | '/$tenantSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TenantSlugRouteRoute: typeof TenantSlugRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  DailyOperationsRoute: typeof DailyOperationsRoute
  DashboardRoute: typeof DashboardRoute
  KioskRoute: typeof KioskRoute
  ManagerRoute: typeof ManagerRoute
  MusammiRoute: typeof MusammiRoute
  PlatformAdminRoute: typeof PlatformAdminRoute
  PrelaunchAuditRoute: typeof PrelaunchAuditRoute
  ProgramSupervisorRoute: typeof ProgramSupervisorRoute
  RegisterRoute: typeof RegisterRoute
  SecretaryRoute: typeof SecretaryRoute
  StaffAttendanceRoute: typeof StaffAttendanceRoute
  StudentRoute: typeof StudentRoute
  SupervisorRoute: typeof SupervisorRoute
  TeacherRoute: typeof TeacherRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantSlug': {
      id: '/$tenantSlug'
      path: '/$tenantSlug'
      fullPath: '/$tenantSlug'
      preLoaderRoute: typeof TenantSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily-operations': {
      id: '/daily-operations'
      path: '/daily-operations'
      fullPath: '/daily-operations'
      preLoaderRoute: typeof DailyOperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager': {
      id: '/manager'
      path: '/manager'
      fullPath: '/manager'
      preLoaderRoute: typeof ManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/musammi': {
      id: '/musammi'
      path: '/musammi'
      fullPath: '/musammi'
      preLoaderRoute: typeof MusammiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform-admin': {
      id: '/platform-admin'
      path: '/platform-admin'
      fullPath: '/platform-admin'
      preLoaderRoute: typeof PlatformAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prelaunch-audit': {
      id: '/prelaunch-audit'
      path: '/prelaunch-audit'
      fullPath: '/prelaunch-audit'
      preLoaderRoute: typeof PrelaunchAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/program-supervisor': {
      id: '/program-supervisor'
      path: '/program-supervisor'
      fullPath: '/program-supervisor'
      preLoaderRoute: typeof ProgramSupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secretary': {
      id: '/secretary'
      path: '/secretary'
      fullPath: '/secretary'
      preLoaderRoute: typeof SecretaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-attendance': {
      id: '/staff-attendance'
      path: '/staff-attendance'
      fullPath: '/staff-attendance'
      preLoaderRoute: typeof StaffAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantSlug/': {
      id: '/$tenantSlug/'
      path: '/'
      fullPath: '/$tenantSlug/'
      preLoaderRoute: typeof TenantSlugIndexRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/kiosk': {
      id: '/$tenantSlug/kiosk'
      path: '/kiosk'
      fullPath: '/$tenantSlug/kiosk'
      preLoaderRoute: typeof TenantSlugKioskRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/manager': {
      id: '/$tenantSlug/manager'
      path: '/manager'
      fullPath: '/$tenantSlug/manager'
      preLoaderRoute: typeof TenantSlugManagerRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/musammi': {
      id: '/$tenantSlug/musammi'
      path: '/musammi'
      fullPath: '/$tenantSlug/musammi'
      preLoaderRoute: typeof TenantSlugMusammiRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/program-supervisor': {
      id: '/$tenantSlug/program-supervisor'
      path: '/program-supervisor'
      fullPath: '/$tenantSlug/program-supervisor'
      preLoaderRoute: typeof TenantSlugProgramSupervisorRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/secretary': {
      id: '/$tenantSlug/secretary'
      path: '/secretary'
      fullPath: '/$tenantSlug/secretary'
      preLoaderRoute: typeof TenantSlugSecretaryRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/staff-attendance': {
      id: '/$tenantSlug/staff-attendance'
      path: '/staff-attendance'
      fullPath: '/$tenantSlug/staff-attendance'
      preLoaderRoute: typeof TenantSlugStaffAttendanceRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/student': {
      id: '/$tenantSlug/student'
      path: '/student'
      fullPath: '/$tenantSlug/student'
      preLoaderRoute: typeof TenantSlugStudentRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/supervisor': {
      id: '/$tenantSlug/supervisor'
      path: '/supervisor'
      fullPath: '/$tenantSlug/supervisor'
      preLoaderRoute: typeof TenantSlugSupervisorRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
    '/$tenantSlug/teacher': {
      id: '/$tenantSlug/teacher'
      path: '/teacher'
      fullPath: '/$tenantSlug/teacher'
      preLoaderRoute: typeof TenantSlugTeacherRouteImport
      parentRoute: typeof TenantSlugRouteRoute
    }
  }
}

interface TenantSlugRouteRouteChildren {
  TenantSlugKioskRoute: typeof TenantSlugKioskRoute
  TenantSlugManagerRoute: typeof TenantSlugManagerRoute
  TenantSlugMusammiRoute: typeof TenantSlugMusammiRoute
  TenantSlugProgramSupervisorRoute: typeof TenantSlugProgramSupervisorRoute
  TenantSlugSecretaryRoute: typeof TenantSlugSecretaryRoute
  TenantSlugStaffAttendanceRoute: typeof TenantSlugStaffAttendanceRoute
  TenantSlugStudentRoute: typeof TenantSlugStudentRoute
  TenantSlugSupervisorRoute: typeof TenantSlugSupervisorRoute
  TenantSlugTeacherRoute: typeof TenantSlugTeacherRoute
  TenantSlugIndexRoute: typeof TenantSlugIndexRoute
}

const TenantSlugRouteRouteChildren: TenantSlugRouteRouteChildren = {
  TenantSlugKioskRoute: TenantSlugKioskRoute,
  TenantSlugManagerRoute: TenantSlugManagerRoute,
  TenantSlugMusammiRoute: TenantSlugMusammiRoute,
  TenantSlugProgramSupervisorRoute: TenantSlugProgramSupervisorRoute,
  TenantSlugSecretaryRoute: TenantSlugSecretaryRoute,
  TenantSlugStaffAttendanceRoute: TenantSlugStaffAttendanceRoute,
  TenantSlugStudentRoute: TenantSlugStudentRoute,
  TenantSlugSupervisorRoute: TenantSlugSupervisorRoute,
  TenantSlugTeacherRoute: TenantSlugTeacherRoute,
  TenantSlugIndexRoute: TenantSlugIndexRoute,
}

const TenantSlugRouteRouteWithChildren = TenantSlugRouteRoute._addFileChildren(
  TenantSlugRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TenantSlugRouteRoute: TenantSlugRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  DailyOperationsRoute: DailyOperationsRoute,
  DashboardRoute: DashboardRoute,
  KioskRoute: KioskRoute,
  ManagerRoute: ManagerRoute,
  MusammiRoute: MusammiRoute,
  PlatformAdminRoute: PlatformAdminRoute,
  PrelaunchAuditRoute: PrelaunchAuditRoute,
  ProgramSupervisorRoute: ProgramSupervisorRoute,
  RegisterRoute: RegisterRoute,
  SecretaryRoute: SecretaryRoute,
  StaffAttendanceRoute: StaffAttendanceRoute,
  StudentRoute: StudentRoute,
  SupervisorRoute: SupervisorRoute,
  TeacherRoute: TeacherRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
